namespace Lochs.AutoGenerated.Ast
{
    public abstract class Expr { }


public class Binary : Expr
{
    public Expr Left { get; set; }
public Token Operator { get; set; }
public Expr Right { get; set; }
    public Binary
    (
        Expr @left, Token @operator, Expr @right
    ) 
    {
        this.Left = @left;
this.Operator = @operator;
this.Right = @right;
    }
}
        

public class Grouping : Expr
{
    public Expr Expression { get; set; }
    public Grouping
    (
        Expr @expression
    ) 
    {
        this.Expression = @expression;
    }
}
        

public class Literal : Expr
{
    public object Value { get; set; }
    public Literal
    (
        object @value
    ) 
    {
        this.Value = @value;
    }
}
        

public class Unary : Expr
{
    public Token Operator { get; set; }
public Expr Right { get; set; }
    public Unary
    (
        Token @operator, Expr @right
    ) 
    {
        this.Operator = @operator;
this.Right = @right;
    }
}
        
}


