using System.Text;
using Lochs.AutoGenerated.Ast;

namespace Lochs
{
    public class ReversePolishNotationPrinter : IAstPrinter, IVisitor<string>
    {
        public string Print(Expr expr)
        {
            return expr.Accept(this);
        }

        public string VisitBinary(Binary binary)
        {
            var lhs = binary.Left.Accept(this);
            var rhs = binary.Right.Accept(this);

            return $"{lhs} {rhs} {binary.Operator.Lexeme}";
        }

        public string VisitGrouping(Grouping grouping)
            => $"({grouping.Expression.Accept(this)})";

        public string VisitLiteral(Literal literal)
            => literal.Value?.ToString() ?? "nil";

        public string VisitUnary(Unary unary)
            => $"{unary.Right} {unary.Operator}";
    }
}
